/**
 * Type-level snake_case -> camelCase conversion, used to derive the API-facing
 * record types from the DB row models generated by Kanel (src/db/models).
 * Rows are snake_case (physical truth); the API speaks camelCase (SQL aliases
 * in the repositories do the runtime mapping - this does the type mapping).
 */

type CamelCase<S extends string> = S extends `${infer Head}_${infer Tail}`
  ? `${Head}${Capitalize<CamelCase<Tail>>}`
  : S;

export type Camelize<T> = {
  [K in keyof T as CamelCase<K & string>]: T[K];
};
